<?binding.jca GetInspectionData_db.jca?>
<wsdl:definitions name="GetInspectionData" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/InspectionApprovalWorkflow/InspectionApproval/GetInspectionData" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/InspectionApprovalWorkflow/InspectionApproval/GetInspectionData" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetInspectionData">
    <plt:partnerLinkType name="GetInspectionData_plt">
        <plt:role name="GetInspectionData_role">
            <plt:portType name="tns:GetInspectionData_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetInspectionData" schemaLocation="xsd/GetInspectionData_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="GetInspectionDataSelect_inputParameters">
        <wsdl:part name="GetInspectionDataSelect_inputParameters" element="top:GetInspectionDataSelect_shidInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxInspectionDataCollection_msg">
        <wsdl:part name="XxInspectionDataCollection" element="top:XxInspectionDataCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetInspectionData_ptt">
        <wsdl:operation name="GetInspectionDataSelect">
            <wsdl:input message="tns:GetInspectionDataSelect_inputParameters"/>
            <wsdl:output message="tns:XxInspectionDataCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
