<?binding.jca UpdateBPMReadyFlag_db.jca?>
<wsdl:definitions name="UpdateBPMReadyFlag" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/InspectionApprovalWorkflow/InspectionApproval/UpdateBPMReadyFlag" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/InspectionApprovalWorkflow/InspectionApproval/UpdateBPMReadyFlag" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateBPMReadyFlag">
    <plt:partnerLinkType name="UpdateBPMReadyFlag_plt">
        <plt:role name="UpdateBPMReadyFlag_role">
            <plt:portType name="tns:UpdateBPMReadyFlag_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateBPMReadyFlag" schemaLocation="xsd/UpdateBPMReadyFlag_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="RcvShipmentLinesCollection_msg">
        <wsdl:part name="RcvShipmentLinesCollection" element="top:RcvShipmentLinesCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateBPMReadyFlag_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:RcvShipmentLinesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
